spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dealer_db
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.example.dealervehicle: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  jwtSecret: ZmFrZV9qb3RfYXV0aF9zZWNyZXRfMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  jwtExpirationSeconds: 3600
