spring:
  datasource:
    url: jdbc:h2:mem:dealer_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.example.dealervehicle: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  jwtSecret: ZmFrZV9qb3RfYXV0aF9zZWNyZXRfMTIzNDU2Njc4OTA=
  jwtExpirationSeconds: 3600
